### ISSUE TITLE
Custom cookie name for sessions

### ISSUE THREAD

**Issue by juliomenendez** [kennethreitz/responder#100]
Would be great if the cookie name used for sessions can be customized but right now `"Responder-Session"` is hardcoded.

**Comment by JayjeetAtGithub** [comment]
from where shall the custom cookie name come ?

**Comment by juliomenendez** [comment]
It could be passed as an argument to the `API` constructor.

**Comment by JayjeetAtGithub** [comment]
Added custom cookie name for sessions. Pls review the PR.
https://github.com/kennethreitz/responder/pull/102

**Comment by JayjeetAtGithub** [comment]
Added None type check to api object in Request class
https://github.com/kennethreitz/responder/pull/103
