### ISSUE TITLE
API.run(..., debug=True) no use

### ISSUE THREAD

**Issue by sandro-qiang** [kennethreitz/responder#145]
API._dispatch or API._dispatch_request catched all exceptions. make uvicorn's _DebugResponder no use.
 All error only returned "Application Error" .

**Comment by TunnelBlanket** [comment]
Same thing for me..

**Comment by steinnes** [comment]
Sam here :-/

**Comment by steinnes** [comment]
Could it be related to this development: https://github.com/kennethreitz/responder/commit/b61feafe5ac6b2cb8bed2bdd138fa47672ba2cbe#diff-554e129ce3806dd33d00eac71a9a086eR258

Which neatly returns 500 on error, but I assume something else needs to happen for at least the stack trace to get printed out.  I tried adding a nasty `raise` on line 278 in my local responder/api.py and now I get the stack both in my browser and my terminal console.

**Comment by tomchristie** [comment]
Behaviour to resolve this: The handler ought to issue the 500 response and then *raise the error*. (So that it is visible to the server for error logging, and to any exception monitoring middleware)

**Comment by steinnes** [comment]
![image](https://user-images.githubusercontent.com/1097582/47516104-1d0d0a80-d874-11e8-8d01-5ca75e1185c1.png)

Since my routes are all function based, the highlighted line in the screenshot above (278 in `responder/api.py`) was enough to see the errors on my machine, but I imagine @tomchristie has something more elaborate in mind?

**Comment by kennethreitz** [comment]
I'm down!

**Comment by steinnes** [comment]
PR coming up :-)

**Comment by tomchristie** [comment]
> I imagine @tomchristie has something more elaborate in mind?

Nothing more elaborate, that `raise` is exactly correct.

**Comment by steinnes** [comment]
Cool.  I wasn't quite sure how to keep the `test_500` test as it was, so I added the exception middleware from starlette, and used that to catch the ValueError raised there.  Here's the PR: https://github.com/kennethreitz/responder/pull/157
