### ISSUE TITLE
Tests fails when Debug=True

### ISSUE THREAD

**Issue by taoufik07** [kennethreitz/responder#174]
When debug is set to True, the tests fails with the following 
```
RuntimeError: Caught handled exception, but response already started.
```
It's not a bug or something,  it happens when debug is True and the ExceptionMiddleware and the DebugMiddleware are used together. **Well they do what they were built to do**.

So I suggest to explicitly  set debug to False in conftest PR #175

**Comment by tomchristie** [comment]
> and the ExceptionMiddleware and the DebugMiddleware are used together

Don’t use them both. ExceptionMiddleware takes a debug=True|False which handles issuing traceback responses. You don’t need the (simpler) DebugMiddleware too.
