### ISSUE TITLE
Feature request: Django-style middleware

### ISSUE THREAD

**Issue by simonpercivall** [kennethreitz/responder#176]
(Sorry if you don't want feature requests in this form.)

https://docs.djangoproject.com/en/2.1/topics/http/middleware/

IMO, Django-style middleware would make for a very nice addition to responder. Specifically, the way to easily write a function middleware that, like a context manager, wraps the request-response logic, makes for very readable and consistent handling. You know from the form of the code directly what happens in a middleware on an exception, or a normal request, and so on.

**Comment by kennethreitz** [comment]
I think you can do that now by just writing a decorator!
