### ISSUE TITLE
Replace the memoize decorator in routes.py by functools.lru_cache

### ISSUE THREAD

**Issue by rparrapy** [kennethreitz/responder#183]
While implementing memoization from scratch is not hard, it does seem a bit like reinventing the wheel. Can we replace the _memoize_ decorator in **routes.py** with _functools.lru_cache(maxsize=None)_? This would also require removing lines that access _._memo_ directly in _test_incoming_matches_.

I guess the underlying question is, do we really need access to the underlying cache implementation (_._memo_)?

If the change is ok, I volunteer to write the PR.

**Comment by kennethreitz** [comment]
sounds good to me!
