### ISSUE TITLE
Mounts and routes are not evaluated in insertion order, which means that a route cannot override something having the same prefix as a mounted app

### ISSUE THREAD

**Issue by hartym** [kennethreitz/responder#186]
Not sure about whether this is intended or not, and if it is starlette or responder's responsibility.

Let's say you're doing something in the line of:
```
api.add_route('/graph', responder.ext.GraphQLView(...))
api.mount('', api.whitenoise)
```

The goal for me is to say the following : 
- If it matches /graph, then go to graphqlhandler
- Otherwise, it may be a static asset so serve it

This thing does not work at all because path are matched against apps prefix before the routes actually are looked into. If a prefix matches, then the app takes over, period.

It is maybe intended, but not intuitive nor I can figure out how to achieve my goal (for now, there may be something, of course).

**Comment by taoufik07** [comment]
Somethine like github.com/taoufik07/responder/tree/apps-routes-resolve ?

**Comment by taoufik07** [comment]
And don't use an empty route for now

**Comment by guptarohit** [comment]
I also faced the issue `"route cannot override something having the same prefix"`.

With following code:
```python
@api.route("/hello/{who}")
def hello_to(req, resp, *, who):
    resp.text = f"hello, {who}!"

@api.route("/hello/{who}/json")
def hello_to(req, resp, *, who):
    resp.media = {"message": [{"name": who}, {"name_again": who}]}
```

While requesting endpoint `"/hello/guido/json"`, getting response:

`hello, guido/json!`

instead following response is expected:

```
- {name: guido}
- {name_again: guido}
```

**Comment by kennethreitz** [comment]
A PR to fix this would be welcome!

**Comment by taoufik07** [comment]
on it

**Comment by taoufik07** [comment]
@guptarohit can you please check if #195 is working ?

**Comment by guptarohit** [comment]
now it's working as expected, thanks @taoufik07 :cake: :sparkles:
