### ISSUE TITLE
api.route("") returns Not Found

### ISSUE THREAD

**Issue by taoufik07** [kennethreitz/responder#189]
When an empty route is provided it returns `404`
```
@api.route("")
def test(req, resp):
    resp.text += "test"
```
I'm gonna write a quick patch to fix that.

-//
@kennethreitz is it time to add some `append_slashes` param  ?

**Comment by taoufik07** [comment]
I know, but what I'm talking about it here is to automatically append or remove slashes.

**Comment by Serkan-devel** [comment]
oh ok

**Comment by kennethreitz** [comment]
I think we're good as-is.
