### ISSUE TITLE
Websocket can't work properly

### ISSUE THREAD

**Issue by zkonge** [kennethreitz/responder#190]
When I sent a websocket request in browser, a 500 error appeared. Then I find something interesting in api.py.[api.py#L222](https://github.com/kennethreitz/responder/blob/master/responder/api.py#L222)
It seems that 'models.Request' is not ready for websocket yet (accept 'http' not 'ws'). Do you have any plan to complete the feature?

These are my test code.
```python
import responder

api = responder.API()

@api.route('/ws', websocket=True)
async def wsk(ws):
    await ws.accept()
    await ws.send_text("Hello via websocket!")
    await ws.close()

api.run()
```
```javascript
const st = new WebSocket('ws://localhost:5042/ws');

st.addEventListener('message', function (event) {
    console.log('Message from server ', event.data);
});
```

**Comment by taoufik07** [comment]
It's under redesign

**Comment by Serkan-devel** [comment]
Are websockets even documented here?

**Comment by taoufik07** [comment]
They were, but now nope

**Comment by kennethreitz** [comment]
what's the problem?

**Comment by taoufik07** [comment]
@kennethreitz aren't you redesigning them ??

**Comment by zkonge** [comment]
In [api.py](https://github.com/kennethreitz/responder/blob/c65e585493688454af062bc0884f44949799d91b/responder/api.py#L223), `models.Request` is used whatever the request protocol is http or websocket, but in [starlette.Response.py](https://github.com/encode/starlette/blob/34d0097feb6f057bd050d5057df5a2f96b97384e/starlette/requests.py#L27), which shows that the `Request` should only instantiate when it's a http request.

**Comment by kennethreitz** [comment]
PRs accepted!

**Comment by frankli0324** [comment]
@kennethreitz  to whom you are replying to? if i may ask

**Comment by taoufik07** [comment]
@kennethreitz I guess we need to close this
