### ISSUE TITLE
Clarification on starlette

### ISSUE THREAD

**Issue by lowlevelware** [kennethreitz/responder#193]
You have cited that responder is powered by starlette, does this mean all features supported by starlette can be used in responder or is it limited to the features listed and described in the [responder documentation](http://python-responder.org/en/latest/)?

Asking specifically about features like [Routing](https://www.starlette.io/routing/), [WebSocket](https://www.starlette.io/websockets/), and [WebSocketEndpoint](https://www.starlette.io/endpoints/#websocketendpoint)

**Comment by kennethreitz** [comment]
It does not.
