### ISSUE TITLE
Unable to include "parameters" in autogenerated documentation

### ISSUE THREAD

**Issue by emacsuser123** [kennethreitz/responder#202]
Hello.

First of all, I would like to say thanks for providing this package.

I'm stuck trying to include a parameters section in the docstring associated to my route functions.
Using the Pets example, I always get the following error for docstrings containing the parameters section, when visiting the /docs path:

> 😱 Could not render this component, see the console.

If no parameters section is included, no error is fired.

I'm including below the whole source code, for your reference.
I have made some slight modifications:
- added "Pet" class, which seems to be needed according to marshmallow documentation.
- added a new route, with pet_id as a path param.
- added a summary section to the docstring

By the way, when you use the directive @api.schema('Pet'), I assume that it adds the schema class following it to the api instance, right? But, what does the param "Pet" do?  I thought that it was used to
automatically create the Pet class (the regular class, not the schema class), but I guess that it is only
a unique name or so...

I'm using python 3.7, and installed the latest stable release with:

> $ pipenv install responder --pre

```
#! /usr/bin/env python
import responder
from marshmallow import Schema, fields

api = responder.API(title='Web Service', version='1.0', openapi='3.0.0',
                    docs_route='/docs')


class Pet():
    def __init__(self, pet_id, pet_name):
        self.pet_id = pet_id
        self.pet_name = pet_name


@api.schema('Pet')
class PetSchema(Schema):
    pet_id = fields.Str()
    pet_name = fields.Str()


@api.route('/pets')
def get_all_pets(req, resp):
    '''A cute furry animal endpoint.
    ---
    get:
        summary: Animal endpoint.
        description: Get all pets.
        responses:
            200:
                description: All pets to be returned
                schema:
                    $ref = '#/components/schemas/Pet'
    '''
    resp.media = PetSchema().dump({'name': 'little orange'}).data


@api.route('/pets/{pet_id}')
def get_one_pet(req, resp, *, pet_id):
    '''A cute furry animal endpoint.
    ---
    get:
        summary: Animal endpoint.
        description: Get a random pet.
        parameters:
            - name: pet_id
              in: path
              description: Pet ID
              type: integer
              required: true
        responses:
            200:
                description: A pet to be returned
                schema:
                    $ref = '#/components/schemas/Pet'
    '''

    pet = Pet('pet_id1', 'freddie')
    resp.media = PetSchema().dump(pet).data


if __name__ == '__main__':
    api.run()
```

Thanks a lot.
-Bob V

**Comment by kennethreitz** [comment]
this looks like it should be working

**Comment by emacsuser123** [comment]
Thanks for the prompt response.
I'm also attaching a snapshot of the web doc page where you can see in the console that react says something like:
"cannot read property get of undefined".


![screenshot from 2018-11-06 13-07-03](https://user-images.githubusercontent.com/16015875/48063334-ff6d6880-e1c4-11e8-8a22-8416d29180fe.png)

**Comment by kennethreitz** [comment]
this might be a bug in apistar @tomchristie

**Comment by emacsuser123** [comment]
OK, I'll open it up, thanks.
BTW, what is the purpose of the parameter in the @api.schema directive?  Is it used to provide it a unique name?

**Comment by emacsuser123** [comment]
My bad .... I've just found what the problem was.
The type must be a subsection of schema.  Something like the following:

  ```
      parameters:
            - name: pet_id
              in: path
              description: Pet ID
              required: true
              schema:
                  type: integer
```

If I use that format in the docstring, documentation page shows with no errors.

Thanks a lot.
