### ISSUE TITLE
Cannot await for body in PUT/POST request

### ISSUE THREAD

**Issue by emacsuser123** [kennethreitz/responder#206]
Hello.

As per the documentation, if you’re expecting to read any request data, on the server, you need to declare your view as async and await the content.

But when I declare a put (or a post) function on a route like the following:

```
async def on_put(self, req, resp, *, app_id):
    data = await req.text()
    resp.text = (f'Obtained HTTP {req.method} request for app-id: {app_id}'
                 f' and body: {data}')
```

I always get an error:

> ./api_server.py:308: RuntimeWarning: coroutine 'Request.text' was never awaited
>   data = await req.text()
> /home/roberto/.local/share/virtualenvs/hpms-okBXuRxW/lib/python3.7/site-packages/responder/api.py:369: RuntimeWarning: coroutine 'BackgroundQueue.__call__' was never awaited
>   self.background(self.default_response, req, resp, error=True)

Thanks.
-Bob V

**Comment by taoufik07** [comment]
use `data = await request.text`, no need to call it, cause it's a property

**Comment by emacsuser123** [comment]
I already did it, but I got the same error.

**Comment by taoufik07** [comment]
Are you using  CBV or just functions ?

**Comment by emacsuser123** [comment]
Class-based.

In fact, my method looks like the following:

```
@api.route('/apps/{app_id}')
class PutAppResource:
    """
    An Application endpoint.
    ---
    put:
        description: Update/Create info for given app-id
        parameters:
            - name: app_id
              in: path
              description: Application ID
              required: true
              schema:
                  type: string
            - name: url
              in: body
              description: URL template used to contact the given application
              required: true
              schema:
                  type: string
                  example: http://example.com/api
        responses:
            200:
                description: Application was successfully created/updated
            500:
                description: Application information could not be processed.
    """
    async def on_put(self, req, resp, *, app_id):

        data = await req.text

        resp.text = (f'Obtained HTTP {req.method} request for app_id: {app_id}'
                     f' and body: {data}')

```

**Comment by taoufik07** [comment]
it's a bug that have something to do with the encoding and we need also to await for the background task and raise the exception

**Comment by emacsuser123** [comment]
OK, thanks a lot for the help.

**Comment by taoufik07** [comment]
@kennethreitz The encoding is not detected automatically

**Comment by emacsuser123** [comment]
@taoufik07 With your patch applied, it still fails, but it gives a different error. Now, the await expression on the request handler says:

> TypeError: object method can't be used in 'await' expression

for the code:

`data = await req.media
`
If I remove the await word on the statement, it does not fail, but the content is not obtained. I guess the method itself is returned, without calling it or something like that:

> <bound method Request.media of <responder.models.Request object at 0x7f779c69cf68>

So, if I do:  await req.media if fails because the object method cannot be awaited, and if I remove the await, the method is not called.

Based on this, I have called the method using:

`        data = await req.media()
`

Now, it makes some more progress, but the json decoding fails with:

>  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


thanks.
-Bob V

**Comment by taoufik07** [comment]
Hi, the patch has nothing to do with the problem, it was for awating background task and raise errors if there's any and since you've got the error it means it's working.

I've mentioned the issue that causes the problem in https://github.com/kennethreitz/responder/issues/206#issuecomment-436316958, when no content is sent aka `b''`, `apparent_encoding` method can't detect the encoding and returns None and an encoding error is raised.
