### ISSUE TITLE
Server Error for objects that are not JSON serializable

### ISSUE THREAD

**Issue by friedrichschoene** [kennethreitz/responder#208]
Within a view function setting `resp.media` throws an `Internal Server Error` if the object is not JSON serializable.
This is due to the `format_json`-method in [formats.py](https://github.com/kennethreitz/responder/blob/7a250aa8fc63389c66b84c73d0cf6085b3f5d42b/responder/formats.py#L28)

I am guessing that the `format_yaml`-method shows a similar behavior.

My proposal to solve this issue is the implementation of a new annotation like this:

    @api.media_encoder(UnserializableClass)
    def my_encoder(obj):
        ...

If I have permission I would write the PR.

**Comment by steinnes** [comment]
You can clone the repository and make a PR from your own repo.
