### ISSUE TITLE
Is it possible to use async/await with GraphQL?

### ISSUE THREAD

**Issue by thebenwaters** [kennethreitz/responder#210]
I wanted to use something like  [this](https://github.com/graphql-python/graphql-core/issues/63) (from graphene-python), but it doesn't seem possible here

Basically I want to async my resolver in GraphQL

Are the current features in `responder.ext.GraphQLView` basic?

**Comment by kennethreitz** [comment]
I believe not

**Comment by Serkan-devel** [comment]
can that be changed?

**Comment by tomchristie** [comment]
If anyone wants to take a crack, have a look at the equivalent in Starlette, which documents using an async resolver. I except it’s either very little work to support it in Responder, or that it just needs docs on how to integrate it.

**Comment by thebenwaters** [comment]
Yeah in aiohttp-graphql you can see the specific code the use to get an async executor to work. Could definitely be implemented with a bit of work.
