### ISSUE TITLE
ModuleNotFoundError when running responder on Python 3.6.6

### ISSUE THREAD

**Issue by BolajiOlajide** [kennethreitz/responder#226]
<img width="284" alt="screenshot 2018-11-14 at 9 10 48 pm" src="https://user-images.githubusercontent.com/25608335/48509573-c7fc5d00-e851-11e8-8d7c-32e1f01d2ae0.png">

The content of `main.py` is as follows:

```
import responder

api = responder.API()

if __name__ == "__main__":
    api.run(port=5000)
```

I get the `ModuleNotFoundError: No module named 'wsgiadapter'` error when I run responder on Python 3.6.6, when I run it on Python 3.7.1 it works fine.

**Comment by kennethreitz** [comment]
I doubt you have your 3.6.6 virtualenv setup properly.

**Comment by BolajiOlajide** [comment]
Hey @kennethreitz , I'm sorry to bother I know you're busy but do you mind clarifying this.

I noticed it throws the same error for Python3.7 also. After hours of trying out different things, I noticed that if I should install responder with `Pip` it works fine but it's when I do so with `pipenv install responder --pre` I get the error.
