### ISSUE TITLE
Streaming response support?

### ISSUE THREAD

**Issue by ClericPy** [kennethreitz/responder#237]
How can I implement streaming response like sanic and flask?

flask:
http://flask.pocoo.org/docs/1.0/api/#flask.stream_with_context
sanic:
https://sanic.readthedocs.io/en/latest/sanic/streaming.html#response-streaming
bottle:
https://bottle.readthedocs.io/en/latest/async.html#greenlets-to-the-rescue

like:
```
resp.stream = generator()
```

Responder is awesome, but I could not find a solution in https://python-responder.org/en/latest/, 
and starlette implement https://www.starlette.io/responses/#streamingresponse.
Using Middleware is another choice.

**Comment by taoufik07** [comment]
see #308
