### ISSUE TITLE
Background task issue (docs and response)

### ISSUE THREAD

**Issue by here0to0learn** [kennethreitz/responder#238]
The background tasks example has a typo:
```data = await req.media()```
should be :
```data = await req.media("form")```

Moreover, when trying to execute the example, the server always returns `null` as response and not what it intends to `{"Success": "True"}`

**Full code:**
```
api = responder.API(title=TITLE, version=VERSION, openapi="3.0.0", docs_route="/docs")

class Test:

    @api.route("/incoming")
    async def receive_incoming(req, resp):
        """Test

        ---
        post:
            description: Hello
            parameters:
              - in: body
                schema: DataSchema
            responses:
                200:
                    description: ok
        """

        @api.background.task
        def process_data(data):
            """Just sleeps for three seconds, as a demo."""
            time.sleep(3)


        # Parse the incoming data as form-encoded.
        # Note: 'json' and 'yaml' formats are also automatically supported.
        data = await req.media("form")

        # Process the data (in the background).
        process_data(data)

        # Immediately respond that upload was successful.
        resp.media = {'success': True}

if __name__ == '__main__':
    api.serve(address="127.0.0.1", port=8081)
```
Response:
`null`

**Comment by sanchitrk** [comment]
are you making a POST request of GET ??

**Comment by here0to0learn** [comment]
It is from the example [here](https://python-responder.org/en/latest/quickstart.html#receiving-data-background-tasks). I don't think there is a specific marker for a POST (at least the documentation doesn't say so).

**Comment by sanchitrk** [comment]
you are right I followed the same, when the browser makes GET request it seems the response is null, I tried POST like `curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:5042/incoming` it returned `{'success': True}` - I guess the docs need updating

**Comment by here0to0learn** [comment]
I am sending the requests from the swagger page to test. It does send a POST to the endpoint. Nothing wrong on the client side that i could find.

**Comment by taoufik07** [comment]
When no param is specified `req.media()` default to JSON and the `JSONDecodeError` is because you're sending a malformed JSON payload (empty string is not a valid JSON).
