### ISSUE TITLE
Using debug=True to reload a file when changed

### ISSUE THREAD

**Issue by antrod** [kennethreitz/responder#239]
Hi, I see from the code that doing:

>> api = responder.API(debug=True)

That should be passed down to uvicorn and cause it to reload on [changes to the file](https://github.com/encode/uvicorn/issues/98)?

However this doesn't seem to work for me running on 1.1.2/Python 3.7.1

**Comment by barrust** [comment]
The passing of debug to uvicorn happens in the call to 
``` python 
api.run(debug=True)
```

Have you tested to see if this method works? It doesn't seem that the debug call in the `API` call is passed around besides in setting the debug setting in some of the middleware calls.

**Comment by here0to0learn** [comment]
With gunicorn, you can pass `--reload` for a similar effect. It restarts the workers.

**Comment by barrust** [comment]
After some more research, it seems that uvicorn does not enable reload on the `uvicorn.run` function. It does on the `uvicorn.main` function, per the code. 

I replicated the logic from `uvicorn.main` in the spawn() sub-method and reload was called, but the changes were not handled correctly. I believe the reload issue is not a responder issue but a uvicorn one.

Thoughts?

**Comment by tomchristie** [comment]
Yes, tho I'd describe it as a limitation, rather than an issue.
Use `uvicorn` from the command line if you want code reloading. (Or `daphne`, or `hypercorn`)

**Comment by barrust** [comment]
That completely makes sense! I was just trying to track the reloading all the way down and got to that point.

**Comment by tomchristie** [comment]
Related: I think we'll want to make uvicorn's "reload" more obviously distinct from "debug". It does enable debug tracebacks too, but they're already handled for you in either the responder or starlette cases anyways.
