### ISSUE TITLE
can responder served by waitress？

### ISSUE THREAD

**Issue by sylvoslee** [kennethreitz/responder#241]

**Comment by therumbler** [comment]
Hi @sylvoslee . No, responder can _not_ be served with Waitress. Waitress is a _WSGI_ server, while Responder is an _ASGI_ app/service.

**Comment by Serkan-devel** [comment]
Maybe there can be an ASGI-equivalent of it somwhere, or you can [mount waitress](https://python-responder.org/en/latest/tour.html#mount-a-wsgi-app-e-g-flask)

**Comment by waghanza** [comment]
@sylvoslee the most known `asgi` servers are 
+ [Hypercorn](https://gitlab.com/pgjones/hypercorn)
+ [Uvicorn](https://github.com/encode/uvicorn)
+ [Daphne](https://github.com/django/daphne)

**Comment by waghanza** [comment]
@sylvoslee I successfully run `responder` via `waitress` in https://github.com/the-benchmarker/web-frameworks/pull/3958
