### ISSUE TITLE
How to reload edits during development 

### ISSUE THREAD

**Issue by lowlevelware** [kennethreitz/responder#251]
The option ‘debug=True’ does not work. It doesn’t reload edits I make to ‘api.py’

How do I live reload responder with closing it and restarting every time. 

I use `uvicorn api:api —debug` to detect file changes but shouldn’t this be the default behaviour when using debug=True?

The documents are not very beginner friendly ;(

**Comment by mmanhertz** [comment]
[Duplicate](https://github.com/kennethreitz/responder/issues/239)
