### ISSUE TITLE
Using responder as a proxy (X-Forwarded)

### ISSUE THREAD

**Issue by Serkan-devel** [kennethreitz/responder#252]
I'm trying to run a small webapp, which sometimes proxies connections to another webservice.
Basically, I want to turn [this nginx configuration](https://git.pleroma.social/pleroma/pleroma-fe/wikis/dual-boot-with-qvitter) but run it as a python app locally because I'm unable to use nginx.

Is there a way to set `X-Forwarded`-headers in a response?

**Comment by mmanhertz** [comment]
According [to the docs](https://python-responder.org/en/latest/quickstart.html#setting-response-headers) you can set any header you want. 
Is there any reason the following wouldn't work?
```
resp.headers['X-Forwarded'] = <whatever you want>
```

**Comment by spyoungtech** [comment]
I think what you're looking for is something like a [Proxy Middleware](https://github.com/webrecorder/wsgiprox). 

However, I'm not familiar with using middlewares with ASGI apps or how compatible (if at all) WSGI middlewares are with ASGI.

**Comment by Serkan-devel** [comment]
But does anyone know what ´$host´ or ´$proxy_add_x_forwarded_for´ from the nginx config actually mean?

**Comment by Serkan-devel** [comment]
@agilezebra considering hst you might know more of nginx than me, how can I convert the variables for the python app?
