### ISSUE TITLE
Route variable rules and more flexible routes

### ISSUE THREAD

**Issue by ibnesayeed** [kennethreitz/responder#254]
Flask allows type declaration in route variables that include `string` (default), `int`, `float`, `path`, and `uuid`. This makes it possible to restrict certain rout matching rules to specific types such as:

```py
@app.route('/posts/<int:post_id>')
```

This will match `/posts/123`, but not `/posts/foo`.

On the other hand, `path` type also accepts values that include forward slashes `/` in them. This is really handy in API's where client is not enforced to URL-encode such values, which is a very commonly practice in the web archiving community (including the Internet Archive) and other services that work on other URLs as their resource identifier. For example, a screenshot service might want to have an API like `/screenshot/<path:remoteurl>` which will work in Flask as expected (when `path` type is specified).

Ruby's [Sinatra framework](http://sinatrarb.com/intro.html) has an even more versatile routing DSL that allows RegEx-based route matching and capture groups in addition to simple path segment rules.

Another thing about Sinatra's routing that I like is that it considers HTTP methods as the first class routing criteria as it is very unlikely that someone would like to execute the same function for more than one HTTP methods on a given route. I know, class-based views in responder allow assigning per-method callbacks, but that approach is not very appealing unless someone is setting up RESTful resource routes.

Are some of these features already possible? If yes, I could not find them in the documentation.

**Comment by taoufik07** [comment]
There's a trick, actually the routing is using f-string syntax, so you can use something like `@api.route("/{x:d}")` for example to accept only integers (other formats : D, f, F, e, g, w )

**Comment by taoufik07** [comment]
#322 #333

**Comment by taoufik07** [comment]
see #333
