### ISSUE TITLE
Italic (cursive??) font in documentation is very difficult to read

### ISSUE THREAD

**Issue by jorng** [kennethreitz/responder#256]
The cursive font in the code blocks of the documentation make the examples very difficult to read, as there is a mix of more traditional monospaced, and the cursive font. A standard monospaced font for all of the code would be much more legible, especially for those with dyslexia and other reading troubles.

<img width="493" alt="screen shot 2018-11-29 at 8 45 28 am" src="https://user-images.githubusercontent.com/7497391/49237585-5b39a480-f3b3-11e8-9460-0597086cf52f.png">

**Comment by jorng** [comment]
Just tried a different computer, and it wasn't cursive, but still not a regular monospaced font. The cursive might be some additional font installed, but still, the "Operator Mono" font seems to be causing issues. It should just be monospace

**Comment by tym-xqo** [comment]
Script italics in Operator Mono are a feature, not a bug. 

https://www.typography.com/blog/introducing-operator

Legibility is in large part a matter of taste. While the point about dyslexia is well-taken, a more varied typeface can dramatically improve code legibility for the colorblind. I myself am neither dyslexic nor colorblind, but switched to Dank Mono (which has similar script italics to Operator) in my editor a while ago and would have a hard time working without script italics now.

**Comment by holdenweb** [comment]
I understand the question of taste (though mine runs more with @jorng than @tym-xqo as it happens). Just the same, it seems perverse for an open source project to deploy what appears to be a commercially-licensed and priced typeface for its documentation.

What am I missing?
