### ISSUE TITLE
Feature request: Trio/Curio support

### ISSUE THREAD

**Issue by beorn** [kennethreitz/responder#260]
Not sure how it would actually look like, but would be great to see support for [Trio](https://github.com/python-trio/trio) (or maybe [Curio](https://github.com/dabeaz/curio) in Responder (and Requests) 🙂

Some others are starting to add support, e.g., [Hypercorn](https://www.reddit.com/r/Python/comments/9xak3w/hypercorn_04_released_hypercorn_is_an_asgi_server/).

**Comment by miracle2k** [comment]
`responder` it seems has only a single import of `asyncio` to test for a coroutine. Basically, support has to be added in `starlette`.
