### ISSUE TITLE
question: how to set httponly status for cookies?

### ISSUE THREAD

**Issue by lowitea** [kennethreitz/responder#265]
how to set httponly status for cookies?

**Comment by kobayashi** [comment]
You can set with `resp.cokkies`. That is described in [Reading/Writing Cookies](https://python-responder.org/en/latest/tour.html#reading-writing-cookies)

**Comment by taoufik07** [comment]
@kobayashi he's talking about directives.
I've made a PR #293 but waiting for @kenneth-reitz approval

**Comment by taoufik07** [comment]
see #293
