### ISSUE TITLE
Recommende way to implement authentication

### ISSUE THREAD

**Issue by vlcinsky** [kennethreitz/responder#270]
For Flask, there are some [authentication snippets](http://flask.pocoo.org/snippets/category/authentication/) e.g. [basic authentication](http://flask.pocoo.org/snippets/8/)

I did not find any authentication example in Responder project.

Is there any?

**Comment by Serkan-devel** [comment]
It does reference  [sessions](http://python-responder.org/en/latest/tour.html#using-cookie-based-sessions) in the docs, but not how to authenticate

**Comment by Serkan-devel** [comment]
This is how it's been done on starlette https://www.starlette.io/authentication/

**Comment by josegonzalez** [comment]
I think you can call `api.add_middleware` and it'll work the same as starlette.

**Comment by tomchristie** [comment]
Starlette's AuthenticationMiddleware would work fine, and would add `auth` into the ASGI scope,
but you also need to implement permissions, that determine what to do, given the authentication/user credentials. (ie. Statlette's `@requires` decorator.)

If responder added an `auth` property on the request (returning the `auth` item from the ASGI scope) then I think the `@requires` decorator would work just fine.

**Comment by gpakosz** [comment]
What should exactly happen so that we can leverage starlette's authentication facility? cc @kenneth-reitz

**Comment by josegonzalez** [comment]
Note: I had to reimplement responder's session handling inside of my custom middleware as the session management from starlette's middleware is incompatible. I'm not sure what the best way forward here is in light of that.

**Comment by fenchu** [comment]
Love to see a best practice implementation here. I have implemented an authenticate decorator using functools wraps like I use in Flask. This works fine for bearer tokens and basic authentication.
