### ISSUE TITLE
Feature request: Implement server side session support 

### ISSUE THREAD

**Issue by prasoon2211** [kennethreitz/responder#272]
Session information is currently being [stored in cookies](https://github.com/kennethreitz/responder/blob/master/docs/source/tour.rst#using-cookie-based-sessions). This causes problems when the session information is set on path `/abc` and needs to be accessed on page `/xyz` - the information set on `/abc` is unavailable on `/xyz`.

The problem can be solved either by:
a. Using a server side session, or,
b. Setting the path for the session cookie (currently named `Responder-Session`) to always be `/`

The second method is easier (and the cookie path should be corrected) but I'm sure server side session storage can be really helpful to some people.

**Comment by tomchristie** [comment]
> Setting the path for the session cookie (currently named Responder-Session) to always be /

Either ways around you'll want to do that, yup.

(If responder used server side sessions it'd *still* need to be setting a session cookie with the ID of the session)

**Comment by josegonzalez** [comment]
Would this be something that would be "fixed" by using Starlette's SessionMiddleware? Right now I'm trying to hack in an OAuthMiddleware to responder and having access to the session in a standard way - either Starlette's or Responder's - would be pretty useful for various reasons.

**Comment by tomchristie** [comment]
Currently not - right now Starlette just has signed-cookie sessions too. We *will* have multiple session backends at some point tho. https://github.com/encode/starlette/issues/284

**Comment by josegonzalez** [comment]
While I wish I had time to contribute the feature - :( - I think I'd be in favor of responder dropping it's session implementation in favor of starlettes, such that responder can then take advantage of any enhancements to upstream's functionality :)
