### ISSUE TITLE
API.add_event_handler doesn't work

### ISSUE THREAD

**Issue by sudiamanj** [kennethreitz/responder#275]
**Python:** 3.7
**OS:** macOS Mojave

As mentioned in the title, I'm attempting to use [add_event_handler](https://python-responder.org/en/latest/api.html#responder.API.add_event_handler), but it doesn't work in the latest version of Responder (**1.2.0**). I'm using version **0.9.9** of Starlette.

Here's what I've tried:

```Python
>>> import responder
>>> api = responder.API()
>>> api.add_event_handler('startup', lambda: print('Starting up...'))
>>> api.add_event_handler('shutdown', lambda: print('Shutting down...'))
>>> api.run()
INFO: Started server process [7003]
INFO: Waiting for application startup.
INFO: Uvicorn running on http://127.0.0.1:5042 (Press CTRL+C to quit)
^CINFO: Stopping server process [7003]
INFO: Waiting for application shutdown.
```

Seems to be a regression, because it does work using `responder==1.1.2` and `starlette==0.8.8`:

```Python
>>> import responder
>>> api = responder.API()
>>> api.add_event_handler('startup', lambda: print('Starting up...'))
>>> api.add_event_handler('shutdown', lambda: print('Shutting down...'))
>>> api.run()
INFO: Started server process [6714]
INFO: Waiting for application startup.
Starting up...
INFO: Uvicorn running on http://127.0.0.1:5042 (Press CTRL+C to quit)
^CINFO: Stopping server process [6714]
INFO: Waiting for application shutdown.
Shutting down...
```

I also tried to use `starlette==0.8.8` with `responder==1.2.0`, but unfortunately that gave me a different issue:

```Python
>>> import responder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/test/lib/python3.7/site-packages/responder/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/anaconda3/envs/test/lib/python3.7/site-packages/responder/core.py", line 1, in <module>
    from .api import API
  File "/usr/local/anaconda3/envs/test/lib/python3.7/site-packages/responder/api.py", line 20, in <module>
    from starlette.middleware.lifespan import LifespanMiddleware
ModuleNotFoundError: No module named 'starlette.middleware.lifespan'
```

**Comment by tomchristie** [comment]
So: Starlette moved from  `LifespanHandler` to `LifespanMiddleware` with 0.9.

The #257 PR resolved an import error, but broke the *actual* functionality. (Presumably it's not test covered.)

**Comment by howaryoo** [comment]
Indeed, with Responder **1.3.0** the event handlers are called fine, however
when the app is used in a pytest  fixture, the event handlers are apparently not called.

This can be an issue if the event handlers are used to initialize something that is dependent of Responder's event loop like an async client to a database.

Any ideas on how to run the event handlers in the pytest fixture or any other recommendation on how 
 to use  Responder's event loop in my db module would be greatly appreciated.

example
API code: myapi.py
```
import responder
api = responder.API()


@api.route("/test")
async def welcome(req, resp):
    resp.media = {
        "Hello": "World",
    }

api.add_event_handler('startup', lambda: print('Starting up...'))
api.add_event_handler('shutdown', lambda: print('Shutting down...'))

if __name__ == "__main__":
    api.run()
```

Fixture: (test/conftest.py)
```
import pytest

import myapi


@pytest.fixture(scope='session')
def server():
    test_api = myapi.api
    return test_api
```

Test code: test/test_api.py
```
def test_test(server):
    r = server.requests.get('test')
    r.raise_for_status()
```

```

**Comment by sudiamanj** [comment]
@howaryoo Try using the test client as a context manager (see [Events](https://www.starlette.io/events/) from Starlette). In your case, you could add another fixture to your conftest like so:

```python
@pytest.fixture(scope='session')
def session(server):
    with server.requests as client:
        yield client
```

And then use the `session` fixture instead of the `server` one.

**Comment by howaryoo** [comment]
@sudiamanj  
Problem solved, thanks a lot.
I am grateful.
