### ISSUE TITLE
GraphiQL integration

### ISSUE THREAD

**Issue by ArtemGordinsky** [kennethreitz/responder#28]
I've noticed some TODO-s mentioning GraphiQL in the code. Does it make sense to integrate it at this point, or is it too soon? 

I would be up for taking a crack at it, if @kennethreitz gives me a thumbs up.

**Comment by kennethreitz** [comment]
it's already built in!

**Comment by kennethreitz** [comment]
oh GraphQL. Yeah, that'd be great if you can do it.

**Comment by ArtemGordinsky** [comment]
Status update:
Got GraphiQL working 🎉
Next up: trying to make sense out of async/await and fixing tests 😅 
<img width="1552" alt="screen shot 2018-10-14 at 17 44 51" src="https://user-images.githubusercontent.com/1506254/46918996-03003c00-cfd9-11e8-9180-71258247918a.png">
