### ISSUE TITLE
Upgrade Starlette pin to 0.10

### ISSUE THREAD

**Issue by tomchristie** [kennethreitz/responder#281]
Release notes: https://www.starlette.io/release-notes/

The only change that needs attention is that JSON-over-websockets is now transmitted as text frames by default, rather than binary frames. (See resolution https://github.com/encode/starlette/pull/349, to issues https://github.com/encode/starlette/issues/332 and https://github.com/encode/starlette/pull/316)

Nominally this is less "correct", but practically it's more sensible. (Support for JSON over binary frames is there, with eg. `websocket.send_json(data, mode="binary")`. I'm not sure what the state of Responders' websockets support is, but I assume you'll want to just upgrade starlette to 0.10.0 without staying with the old"JSON over binary frames" style.

**Comment by taoufik07** [comment]
ref #288
