### ISSUE TITLE
Any way to deploy responder app as an AWS Lambda Function? 

### ISSUE THREAD

**Issue by abhaybhargav** [kennethreitz/responder#282]
Wondering if anyone has tried to run a Responder App as a FaaS AWS Lambda Function. Any known approach or experiments?

**Comment by tomchristie** [comment]
Take a look at 
https://github.com/erm/mangum

**Comment by erm** [comment]
The middleware in Mangum should work with Responder, but the API class creates directories/files by default [here](https://github.com/kennethreitz/responder/blob/master/responder/api.py#L104), this will raise a `Read-only file system` error in AWS Lambda.

Not sure if there is anything on the AWS end to workaround this, but it may only be possible if the templates/staticfiles in Responder are made more configurable - though I don't know how trivial or complex that may be depending on how integrated those definitions are throughout the rest of the API.
