### ISSUE TITLE
static routes give exception on dir listing

### ISSUE THREAD

**Issue by mikeckennedy** [kennethreitz/responder#283]
Hi folks! Just playing around with the library (nice work @kennethreitz !). Ran into a small issue in the docs and in code.

From the docs: It's not clear how to setup a static route to a folder of resources. The only mention is mapping '/' statically for SPAs. Not a major deal but something I noticed.

The error hower is probably worth looking at. If you have a folder structure such as:

```
├── static
│   └── css
│       ├── docs.css
│       └── theme.css
```

And map to this folder to serve up the CSS files as:

`api.add_route("/static", static=True)`

Then requests for the files work fine (e.g. `http://127.0.0.1:5042/static/css/docs.css`). But when requesting `http://127.0.0.1:5042/static/` I was expecting 404 or dir listing not allowed or something. But rather got 500 internal server error.

```
TypeError: 'NoneType' object is not iterable
INFO: ('127.0.0.1', 58711) - "GET /static/ HTTP/1.1" 500
```

We probably don't want 404's to appear as 500 server errors for our logs or the users.

**Comment by taoufik07** [comment]
Hey,

Just to make things clear, static files serving is always enabled, by default it uses `static_dir="static"` and `static_route="/static"`, you can set custom values when you first init `responder.API`.

```python
api = responder.API(..., static_dir="my_static_dir", static_route="/my_route")
```

The `api.add_route("/route", static=True)` is for SPA, by default it looks for an "index.html" in the static dir.

So if you wanna serve static files (css, js,...), you don't need to to use `api.add_route("/", static=True)`

**Comment by mikeckennedy** [comment]
Hi,

I think you missed the problem here because I was screwing around with explicit static routes. 

The problem is if you run responder, the visit the URL http://localhost:5000/static you will get a server 500. That is not the right response.

I was trying to reproduce this but cannot get Responder to run at all now. See #300 for another bug that is preventing it from running.

**Comment by taoufik07** [comment]
@mikeckennedy I'm aware of the bug and I was just trying to make things clear.
I've also made a quick fix #297, it's working but didn't want to merge it for now.

**Comment by mikeckennedy** [comment]
Thanks so much. Sorry I misunderstood you. Much appreciated!

**Comment by taoufik07** [comment]
You're welcome dude, no problem :D
