### ISSUE TITLE
HTTPS Redirect Not working

### ISSUE THREAD

**Issue by jtbaker** [kennethreitz/responder#284]
Hi, I'm having some issues using the `enable_hsts` HTTPS redirect argument on `responder.API` - is there some additional configuration I need to do with the CORS settings? 

I tried doing
```
api = responder.API(enable_hsts=True, 
                    cors=True, 
                    cors_params={'allow_origins': ['*']})
```

No matter what, my server does redirect the client to the HTTPS address, but the server then responds with HTTP 301 status codes. Do I need to do some additional configuration inside of my routes to be able to handle these incoming requests? Or does someone have some production project boilerplate code they could point me to that uses this feature in the module?

Many thanks,

Jason

**Comment by taoufik07** [comment]
it's related to starlette URL data structure, I'm gonna work on it

**Comment by jtbaker** [comment]
Thanks for the quick response @taoufik07! Do you know if there might be a short term fix to drop into the middleware somehow to make it workable for the time being - or where might be a good entry point to start digging on that?

**Comment by taoufik07** [comment]
We need to update the hsts middleware in starlette, I'm gonna push a PR now

**Comment by jtbaker** [comment]
Hey @taoufik07, saw your work over on Starlette [#381](https://github.com/encode/starlette/pull/381). Thanks for taking the time to submit. However, I've re-installed Starlette from git source
`pip uninstall starlette`
then
`pip install git+https://github.com/encode/starlette.git@master`

to make sure my version with current with the master, which the commits have been merged into. However, the HTTPS issue originally experienced here in Responder are still persisting, as before. Are there further edits or changes that need to be made for the feature to function properly?

Thanks!

**Comment by tomchristie** [comment]
The change made in Starlette's HTTPSRedirectMiddleware (https://github.com/encode/starlette/pull/382) ensured that URLs using explicit port numbers outside of 80/443 would still keep the port number after any https redirect.

That's not necessarily relevant to whatever this issue relates to.

Are you seeing the issue in development or on a deployed platform?
How are you including the SSL certificates if you're running in development?

Uvicorn supports being the SSL termination point, but it's only recently added, and I don't think it's exposed in Responder's API.

You won't *typically* want HTTPS redirection to be enabled *in development*, and both Starlette's and Responder's documentation should probably explain why, and point towards how to obtain certificates and enable Uvicorn's SSL support for users that *do* need that.

**Comment by jtbaker** [comment]
In development only right now. I couldn't find anything on [uvicorn](https://www.uvicorn.org/deployment/) or [starlette](https://www.starlette.io/middleware/#httpsredirectmiddleware) docs about such configuration.

I guess the frustrating part about it is that responder [advertises](https://python-responder.org/en/latest/tour.html#hsts-redirect-to-https) the feature, and as having a production webserver builtin, but no direction on how to implement it in a real environment.

I'm relatively new to web development so this seemed like a great option to implement a microservice, but just can't find the documentation on how to actually use this feature, which seems pretty important, especially if my API involves sending or receiving any kind of remotely sensitive information.

**Comment by tomchristie** [comment]
Yeah the docs for both responder and Starlette should do a bit of guideposting there.

In short: Don’t use it in development, do use it in production.

**Comment by jtbaker** [comment]
Thanks for the response @tomchristie! I think I've got an idea on where I need to go from here.
