### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by oldani** [kennethreitz/responder#286]
Hi,

While inspired by responder and build a framework for a talk I found an issue related to `parse` library. Take for instance:

```python
import responder

api = responder.API()

@api.route("/{greeting}")
async def greet_world(req, resp, *, greeting):
    resp.text = f"{greeting}, world!"

if __name__ == '__main__':
    api.run()
```

`/hello/responder` will match `/{greeting}"`, unless we put a `/` at the end of the pattern any route will match it. I suggest that when adding a new route we check if it ends with a `/` and if not add it underthehood.

If you approve it, I will make a PR.

**Comment by taoufik07** [comment]
Already suggested it #189, but @kenneth-reitz said no
