### ISSUE TITLE
Please release version 1.2.1 that contains the fixes from version 1.1.3.

### ISSUE THREAD

**Issue by dbaxa** [kennethreitz/responder#287]
Hi, @kenneth-reitz various fixes were released in version 1.1.3 which are not in 1.2.0, see https://github.com/kennethreitz/responder/compare/v1.2.0...v1.1.3 . Can you please release release a version > 1.2.0 that contains the fixes that are in 1.1.3.

**Comment by timofurrer** [comment]
I've just released **v1.3.0** 🎉
