### ISSUE TITLE
Document how to do file uploads

### ISSUE THREAD

**Issue by alexwlchan** [kennethreitz/responder#294]
After a bit of trial and error (and poking around in the codebase), I think I’ve worked out how to process file uploads:

```python
import responder

api = responder.API()


@api.route("/")
async def upload_file(req, resp):
    
    @api.background.task
    def process_data(data):
        open("uploaded_file.txt", "wb").write(data["file"])
    
    data = await req.media(format="files")
    process_data(data)
    
    resp.media = {"success": "ok"}


if __name__ == "__main__":
    api.run(port=8210)
```

But as far as I can tell, this isn't documented anywhere, and for all I know this has some obvious bug that’s going to cause me grief later. Since responder seems to have support for this, it’d be great to have an example in the docs to show how easy it is!

**Comment by kobayashi** [comment]
You can do that like this.

```python
@api.route("/")
async def upload_file(req, resp):

    @api.background.task
    def process_data(data):
        f = open('./{}'.format(data['file']['filename']), "w")
        f.write(data['file']['content'].decode('utf-8'))
        f.close()

    data = await req.media(format="files")
    process_data(data)

    resp.media = {"success": "ok"}
```

Trying to send with requests.

```python
import requests

data = {"file": ("hello.txt", "hello, world!", "text/plain")}
r = requests.post('http://127.0.0.1:8210/file', files=data)

print(r.text)
```

**Comment by kobayashi** [comment]
For the documentation, [Receiving Data & Background Tasks](https://python-responder.org/en/latest/quickstart.html#receiving-data-background-tasks) seems to be the best place to write down about this sample. Is there any thought?

**Comment by kenneth-reitz** [comment]
agreed!

**Comment by kobayashi** [comment]
PR #335
