### ISSUE TITLE
Different streaming response experience between bottle and responder

### ISSUE THREAD

**Issue by ClericPy** [kennethreitz/responder#311]
### code

responder:
```
import responder
import asyncio

api = responder.API()


@api.route("/")
async def greeting(req, resp):

    @resp.stream
    async def shout_stream():
        for _ in range(10):
            yield '='
            await asyncio.sleep(0.1)


if __name__ == "__main__":
    api.run()
```

bottle:

```
from time import sleep
from bottle import route, run


@route('/')
def stream():
    for _ in range(10):
        yield '='
        sleep(0.1)


run(host='0.0.0.0', port=5042)

```

### Env

Windows 10
python3.7
Bottle 0.11.2
responder 1.3.0
Google Chrome 72.0.3626.96

### Expect

response show string one by one

### Description

1. Both `bottle` and `responder` return same response while typing:
`curl http://127.0.0.1:5042`

yield string one by one

2. Use Chrome 72 open `http://127.0.0.1:5042`

2.1 bottle

yield string one by one

2.2 responder
![image](https://user-images.githubusercontent.com/7133852/53242340-6b75cd00-36df-11e9-9067-0e411d5254c7.png)

**Comment by taoufik07** [comment]
Just tried it on chrome and it's shows `==========`

**Comment by ClericPy** [comment]
ok... maybe it's my own environment bug... thanks a lot

**Comment by taoufik07** [comment]
You can let it open until we make sure

**Comment by ClericPy** [comment]
I tried for 
```
@resp.stream
    async def shout_stream():
        yield 'aaa'
```
It will return aaa on chrome
but 
```
@resp.stream
    async def shout_stream():
        yield 'aaa'
        yield 'aaa'
```
will return ''

**Comment by taoufik07** [comment]
Nope I'm on python 3.6

**Comment by taoufik07** [comment]
I tried with "aaa"*2 and it's working for me, I'm gonna switch to 3.7 and see

**Comment by ClericPy** [comment]
OK, last time I found a issue between default Queue and _Queue on python3.7, which raised on gevent, but it's not be used in this lib. Maybe some different low-level implementation not compatible

**Comment by taoufik07** [comment]
It's working for me with python 3.7

**Comment by ClericPy** [comment]
Windows 10, Python 3.7.1, 
apispec                  1.0.0

I will try some other environment, then comment the new result...

**Comment by ClericPy** [comment]
Some friends tried it on python3.7+MacOS, return '=========' in one time, not one by one.

**Comment by ClericPy** [comment]
I tried it on python3.6.4+CentOS Linux release 7.4.1708, return '=========' in one time, not one by one.

**Comment by ClericPy** [comment]
# add the source code for testing starlette:

```
import asyncio

import uvicorn
from starlette.applications import Starlette
from starlette.responses import StreamingResponse

app = Starlette()


async def slow_numbers(minimum, maximum):
    yield ('<html><body><ul>')
    for number in range(minimum, maximum + 1):
        yield '<li>%d</li>' % number
        await asyncio.sleep(0.5)
    yield ('</ul></body></html>')


@app.route('/')
async def homepage(request):
    generator = slow_numbers(1, 10)
    return StreamingResponse(generator, media_type='text/html')


if __name__ == '__main__':
    uvicorn.run(app, host='127.0.0.1', port=5042)
```

**Comment by ClericPy** [comment]
if I remove `, media_type='text/html'` args, starlette will return '==========' in one time...... so the reason is this args........

**Comment by taoufik07** [comment]
I see now, I thought it was because of the browser rendering buffer.

in responder we have mimetype (I've chosen it, because that's what @kenneth-reitz have used in the Request) `resp.mimetype = "text/html"`, but streaming won't work due to the dispatching in responder

**Comment by JacobHenner** [comment]
What's the status of this bug? I seem to be encountering it in 2.0.5.
