### ISSUE TITLE
Problem to install responder on Windows using `poetry`

### ISSUE THREAD

**Issue by vlcinsky** [kennethreitz/responder#318]
Status about options to install responder on MS Windows:
- `pip`: works well
- `pipenv`: no idea
- `poetry`: it fails on attempt to install `uvloop`

This issue deals with `poetry` problem.

The problem is with `uvicorn` building requirements in code instead of using environment markers. This is currently being worked on [using optional packages](https://github.com/encode/uvicorn/issues/219).

After that issue is resolved and relevant `uvicorn` package released, `responder` will probably have to update it's own environment markers to address new way of working with optional packages as installed by `uvicorn`.

Until then, we cannot do much about it.

**Comment by tomchristie** [comment]
Optional packages for Uvicorn is probably my preferred outcome longer term, but would require a version bump.

We could push a patch release using environment markers in the meantime. Want to open an issue there (perhaps also make the PR if you’re keen to get it sorted)

**Comment by vlcinsky** [comment]
@tomchristie I will consider the environment marker contribution. 

As responder does not have any version requirements to uvicorn, it would improve the issue with installing responder by poetry immediately.

**Comment by vlcinsky** [comment]
WIP: https://github.com/encode/uvicorn/pull/309

**Comment by vlcinsky** [comment]
Since uvicorn==0.4.6 the issue is resolved.

Next major uvicorn version plans to imlement https://github.com/encode/uvicorn/issues/219 which will use extras to control what is to be installed, that time we may need to modify our requirements.
