### ISSUE TITLE
Routes params converters

### ISSUE THREAD

**Issue by taoufik07** [kennethreitz/responder#322]
Hey,

Responder has no documented way to automatically cast route params, since we're using python's string format, "format specifications"/[directives](https://github.com/r1chardj0n3s/parse#format-specification) works out of the box, e.g. `@api.route("{number:d}/")`.

We can either document the method above or create our own converters and have something fancy like `@api.route("{number:int}/")` or `@api.route("<number:int>/")`.

**Comment by taoufik07** [comment]
@kenneth-reitz

**Comment by kenneth-reitz** [comment]
lets get this working!

**Comment by kenneth-reitz** [comment]
any @kennethreitz/ambassador-trainees want to take this on?

**Comment by taoufik07** [comment]
The fancy way ?
