### ISSUE TITLE
dealing with index.html location not in static directory

### ISSUE THREAD

**Issue by KenanHArik** [kennethreitz/responder#323]
Responder is a great package, loving it so far!

Wanted to share some feedback on trouble that I ran into while trying to trying to deal with SPA, specifically dealing with serving up a React SPA bootstrapped by Create-React-App. The default webpack build scripts put the index.html in the parent folder of the static content.

```
/build
  |
  -index.html
  |
  --- /static
       |
       -css/
       |
       - js/
       |
       - media/
```

Because of this deployed layout, I could not figure out how to point to the index.html file and the static directory. Is there any way to point to static directory and index.html separately for add_route method?

For now, my workaround is to fix by moving the index.html file into the static folder, but perhaps there are better ways?

Here is my code for responder with the directory arguments:

```
api = responder.API(static_dir="../build/static", static_route="/static", templates_dir="../build")

api.add_route("/", static=True)

if __name__ == '__main__':
    api.run(port=3001)
```

Thanks!

**Comment by KenanHArik** [comment]
For reference, I have posted the git repository with this project here: https://github.com/KenanHArik/react-responder

**Comment by taoufik07** [comment]
`index.html` needs to be in responder's static directory.
We could add an argument that refers to `index.html`'s path inside responder's static directory.

**Comment by kenneth-reitz** [comment]
no need, symlinks sill suffice.

**Comment by kenneth-reitz** [comment]
fewer knobs, not more knobs
