### ISSUE TITLE
Uvicorn 0.5

### ISSUE THREAD

**Issue by tomchristie** [kennethreitz/responder#326]
Uvicorn 0.5 has been released.

* Auto-reloading will now take effect, without having to use `uvicorn` from the console.
* Multi-worker support is here.

I'd suggest the following:

* Switch `debug=True` to `reload=True` in `uvicorn.run(...)`
* Pin uvicorn to `0.5.*`
* If you want to enable multiworker support (it's not the default *yet*) then use `workers=multiprocessing.cpu_count()`.

**Comment by kenneth-reitz** [comment]
> If you want to enable multiworker support (it's not the default yet)

when will it become default?

**Comment by tomchristie** [comment]
@kenneth-reitz I've not really considered. Trivial code-wise to switch it around, but figured introducing it optionally first would be safest. If there's no reported issues then we can make the switch with 0.6.

As well as `multiprocessing.cpu_count()` I think there's an envvar that we oughta look at, which heroku use, right? (Linked to how many dynos are configured) Don't know if that's in standard use elsewhere or not?

**Comment by tomchristie** [comment]
> "Auto-reloading will now take effect, without having to use uvicorn from the console."

Okay, sadly no, turns out that's not the case. - "spawn" multiprocessing doesn't work reliably enough to allow that.

Uvicorn will only support the programmatic `reload=True` if the the application is passed as an import string, rather than the raw app instance.

Anyway's recommendations since the upgrade:

* Pin uvicorn to 0.5.*
* You may as well drop `debug=True` (You're including starlette's debugging middleware anyways.)

**Comment by kenneth-reitz** [comment]
yes `WEB_CONCURRENCY`.

**Comment by kenneth-reitz** [comment]
Does an @kennethreitz/ambassador-trainees want to handle this?
