### ISSUE TITLE
JSON Decode Error when GET request is made to endpoint which expects a payload

### ISSUE THREAD

**Issue by jlewis91** [kennethreitz/responder#331]
If the web server expects a payload, for requests where the payload is empty, a `JSONDecodeError` is raised. Would it make sense for responder to check whether the payload is empty and then return an empty dictionary?

Minimal Example:

```
import responder

api = responder.API(
    title="Sample API",
    version="1.0",
    openapi="3.0.2",
    docs_route="/docs",
)

@api.route("/test")
async def receive_incoming(req, resp):
    
    data = await req.media()

    resp.media = {}

    return



r = api.requests.get(url=api.url_for(receive_incoming))
```

Error:
```
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by taoufik07** [comment]
You said it expects a payload xD.

\* Responder is using python's standard [json](https://docs.python.org/3.7/library/json.html) library, which follows [RFC 7259](https://tools.ietf.org/html/rfc7159.html).
\* Empty are `""`, `{}` or `[]`.

**Comment by jlewis91** [comment]
Hey! Thanks for the response, sounds totally reasonable. I guess the question I have is what the appropriate way of handling this error is, to ensure that GET requests to POST only endpoints get an informative error message, for example if a 3rd party makes a request to the post endpoint specified in the [quickstart documentation](https://github.com/kennethreitz/responder/blob/2ad351197eaa26f870cf96f1caec69a9b99d6f82/docs/source/quickstart.rst), AFAICT it takes the whole server down.

**Comment by taoufik07** [comment]
You're welcome @jlewis91, a try and catch would do the job.

No it doesn't take the whole server down.
