### ISSUE TITLE
Background tasks and websockets: how to pass data back to view?

### ISSUE THREAD

**Issue by shawnratcliff** [kennethreitz/responder#336]
I've been trying to figure out how to use background tasks with websockets to perform an expensive computation and hand the result back to the client when it completes. For example:

```
@api.route('/ws', websocket=True)
async def websocket(ws):
   
    @api.background.task
    def big_heavy_computation(data)
        time.sleep(10)
        return '42'
    
    await ws.accept()
    data = await ws.receive_text()
    result = await big_heavy_computation(data)
    await ws.send_text(result)
    await ws.close()
```

But this isn't working; the socket is closed and no result is sent. I've also tried adding ```async``` to the background task declaration and calling the ```ws``` object from within it, but that also doesn't work. What's the right way to approach this?

**Comment by kobayashi** [comment]
Could you let me know more specific use case?

If you want to get the result from an another function,  you might not need background tasks. You can do like this.

```
@api.route('/ws', websocket=True)
async def websocket(ws):

    def big_heavy_computation(data):
        time.sleep(10)
        return '42'

    await ws.accept()
    data = await ws.receive_text()
    result = big_heavy_computation(data)
    await ws.send_text(result)
    await ws.close()
```

**Comment by shawnratcliff** [comment]
Hi; thanks for the comment. The use case I'm considering is deep learning inference. The client will send over an image, and that image will be transformed and run through a couple of large neural networks on the CPU. Since these jobs can take a few seconds, I'd like them to queue up and run in the background on the available CPU  cores. When the job is done, the result is sent back over the websocket.

I tried running a test with a regular function, as you suggested. What I found is that if the server receives multiple requests in short succession, the big_heavy_computation isn't parallelized. The first result comes back at t=10, the second at t=20, etc.

**Comment by shawnratcliff** [comment]
I believe I may have found my problem, and a solution. I did not realize that `concurrent.futures.Future` is completely different from `asyncio.Future`, and not `await`-able. However, asyncio (since Python 3.5) provides a `wrap_future` function which appears to bridge them.

The following code appears to work. Any reason not to use it in this way?

```
import asyncio

@api.route('/ws', websocket=True)
async def websocket(ws):

    @api.background.task
    def big_heavy_computation(data):
        time.sleep(10)
        return '42'

    await ws.accept()
    data = await ws.receive_text()
    async_future = asyncio.wrap_future(big_heavy_computation(data))
    result = await async_future
    await ws.send_text(result)
    await ws.close()
```

**Comment by kobayashi** [comment]
Thanks to share that sample!
Background tasks are threading and not async loop inside.

**Comment by howaryoo** [comment]
> Hi; thanks for the comment. The use case I'm considering is deep learning inference. The client will send over an image, and that image will be transformed and run through a couple of large neural networks on the CPU. Since these jobs can take a few seconds, I'd like them to queue up and run in the background on the available CPU cores. When the job is done, the result is sent back over the websocket.
> 
> I tried running a test with a regular function, as you suggested. What I found is that if the server receives multiple requests in short succession, the big_heavy_computation isn't parallelized. The first result comes back at t=10, the second at t=20, etc.

@shawnratcliff , since your use case is CPU bound and not IO bound, the best for you would be to:

* use a process pool instead of the thread pool used by  `@api.background.task`
* or better use a message queue like RabbitMQ, Celery ...

I have a similar use case and use RabbitMQ with `aio-pika` (https://aio-pika.readthedocs.io/en/latest/). The rabbitMQ workers take care of processing the CPU intensive tasks and send the results to the API using websockets when finished.

**Comment by kobayashi** [comment]
close
