### ISSUE TITLE
Serving static files results in 500 Internal Server Error

### ISSUE THREAD

**Issue by jonbeebe** [kennethreitz/responder#337]
Python version: 3.7
Responder version: 1.3.0

Put files in static directory and a 500 Internal Server error results when attempting to access that static files.

Error:

```
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jonbeebe/Library/Python/3.7/lib/python/site-packages/responder/api.py", line 244, in __call__
    return app(scope)
TypeError: __call__() missing 1 required positional argument: 'start_response'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jonbeebe/Library/Python/3.7/lib/python/site-packages/uvicorn/protocols/http/httptools_impl.py", line 371, in run_asgi
    asgi = app(self.scope)
  File "/Users/jonbeebe/Library/Python/3.7/lib/python/site-packages/responder/api.py", line 247, in __call__
    return app(scope)
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
INFO: ('127.0.0.1', 61924) - "GET /static/css/app.css HTTP/1.1" 500
```

**Comment by shawnratcliff** [comment]
I'm having this issue as well. But, curiously, it's only occurring when I run Responder in a Docker container. It doesn't occur with the same source code and same package versions in a virtualenv on my development machine.

**Comment by jonbeebe** [comment]
@shawnratcliff Yes that does sound odd. Mine is not running in a Docker container, but directly on my macOS (10.14) development environment.

**Comment by howaryoo** [comment]
@jonbeebe @shawnratcliff 
it seems that  `asgiref`, one of the dependencies of `responder` got upgraded to version `3.0.0` and causes the error.

The issue goes away if you pin the version of `asgiref` to `2.3.2`

Output of `pipdeptree -p responder`

```
responder==1.3.0                                                                                                                                      
  - aiofiles [required: Any, installed: 0.4.0]
...
  - asgiref [required: Any, installed: 2.3.2]                                                                                                         
    - async-timeout [required: >=2.0,<4.0, installed: 3.0.1] 
...

**Comment by jonbeebe** [comment]
@howaryoo Nice catch! asgiref has a compatibility.py module with the 3.0.0 release that might possibly be able to resolve this issue: https://github.com/django/asgiref/blob/master/asgiref/compatibility.py

**Comment by tomchristie** [comment]
Alternate option: use starlette’s WSGIMiddleware

**Comment by jonbeebe** [comment]
@tomchristie I tried replacing the call to WsgiToAsgi to WSGIMiddleware and while there are no longer any errors, I'm getting a 404 for every request to the static files.

**Comment by axlroden** [comment]
I thought I was doing something wrong with my static files, glad its just dependency issue.

**Comment by tomchristie** [comment]
@jonbeebe I'll happily review any PR making the switch, shouldn't be anything to it, but *shrug*.
Anyways the simplest thing in the meantime would be pinning asgiref to `~=2.*`

**Comment by jonbeebe** [comment]
@tomchristie I'd like to but unfortunately don't know enough about the architecture of Responder to make it work. I'll take a look though

**Comment by jonbeebe** [comment]
@tomchristie I took a look and was unable to get it to work, although I did find some insights that may be helpful.

Around line 272 where `return app(scope)` is called, `app` refers to the `self.whitenoise` instance that is set to _notfound_wsgi_app by default. When the instance is called, it is expecting two arguments but we are only passing one: scope. Not sure how this relates to asgiref exactly but hopefully that helps.

**Comment by jonbeebe** [comment]
@tomchristie disregard my last message — I was able to remove the asgiref dependency and just use starlette's WSGIMiddleware as previously suggested and all works well now. PR forthcoming...

**Comment by taylorperkins** [comment]
🙌

**Comment by bradh11** [comment]
I'm also having this issue - is this resolved now in the latest published revision?

**Comment by ntextreme3** [comment]
@bradh11 me too ... doesn't appear to have been released yet

**Comment by bradh11** [comment]
@kennethreitz - it seems these updates fix the static files issue, but the fix is not yet published to pypi 👆.   Can you check it out and make it public?  See related issue #334
