### ISSUE TITLE
How could I set 'json ensure_ascii = false' when resp.media is Japanese or Chinese?

### ISSUE THREAD

**Issue by songsenand** [kennethreitz/responder#338]
When `resp.media = {'error': '错误的数据类型'}`, I'll get `{"error":  "\\u9519\\u8bef\\u7684\\u6570\\u636e\\u7c7b\\u578b"}`. I know I should set `json ensure_ascii = false` in `json.dumps`, but I don't know how to do that in `responder`.

like that:
``` python
@api.route('/{errorcode}')
async def error(req, resp, *, errorcode):
    resp.media = {
            'errorcode': errorcode,
            'message': '错误的数据类型'
    }
```

Sorry about my English, I really not good at that.
Thanks a lot!

**Comment by axlroden** [comment]
https://github.com/kennethreitz/responder/blob/00211c8f03b24b19aeb70a855d84fab298f0ae9a/responder/formats.py#L24

You'd have to redo that function I guess..

**Comment by songsenand** [comment]
> [responder/responder/formats.py](https://github.com/kennethreitz/responder/blob/00211c8f03b24b19aeb70a855d84fab298f0ae9a/responder/formats.py#L24)
> 
> Line 24 in [00211c8](/kennethreitz/responder/commit/00211c8f03b24b19aeb70a855d84fab298f0ae9a)
> 
>  async def format_json(r, encode=False): 
> You'd have to redo that function I guess..

Thanks for your reply!
Actually, I did this:
```python
async def format_json(r, encode=False):
    if encode:
        r.headers.update({"Content-Type": "application/json"})
        return json.dumps(r.media, ensure_ascii=False)
    else:
        return json.loads(await r.content)

api = responder.API(secret_key=os.urandom(16))
api.formats['json'] = format_json
```
It works well.


I think it is excellent that if there is a more "official" solution in the future.
