### ISSUE TITLE
how server receives 'base64 encoded' data ?

### ISSUE THREAD

**Issue by hamadatakaki** [kennethreitz/responder#352]
I wanna build a server, it must recieve **base64 encoded** data.
how to recieve base64 encoded data on responder...？

I try to use `await req.content' , but it doesn't work...

please teach me what I change this code.

```
# server's class-based view

@api.route('/hoge')
class HogeView:
    async def on_request(self, req, resp):
        content = await req.content
        print(content)    # b''
```

```
# and test client code

if __name__=='__main__':
    def request_test():
        requests.post('http://localhost/hoge', params=base64.b64encode(b'hoge'), headers={'content-type': 'application/octet-stream'})

    request_test()
```

help me!

**Comment by taoufik07** [comment]
Hey, you're passing the arguments via the url params, you can access them in responder via `req.params`.

**Comment by hamadatakaki** [comment]
@taoufik07 
Thanks commet!
I successed getting data!
