### ISSUE TITLE
Duplicated function/method

### ISSUE THREAD

**Issue by Hultner** [kennethreitz/responder#355]
This function already exists on the object, why add an identical one inside the function?
https://github.com/kennethreitz/responder/blob/78b5bef879380146d0bf14b35e0fd618d9694971/responder/api.py#L645-L647

**Original definition:**
https://github.com/kennethreitz/responder/blob/78b5bef879380146d0bf14b35e0fd618d9694971/responder/api.py#L624-L627

**Comment by taoufik07** [comment]
Hey, actually they are not identical, not the prototype :3.

The why ? The apistar template expects a function with `asset` as an argument to and returns its static url. 

What we can do here is something like

```python
def static_url(asset):
    return self.static_url(asset)
```
But I don't know why we didn't do it earlier

**Comment by frostming** [comment]
Closed via #357
