### ISSUE TITLE
Bloated API.__init__

### ISSUE THREAD

**Issue by taoufik07** [kennethreitz/responder#356]
Hello,

The `API.__init__` looks bloated and hard to read, I think it's time to divide and reorganize things. 

I wanna open a discussion to know what you guys think, what do you suggest to make it more readable and modular. we can also discuss a recommended way to make extensions to easily extend the responder.

**Comment by taoufik07** [comment]
cc @kenneth-reitz

**Comment by taoufik07** [comment]
We can start by moving the schema, one of the simple ways would be something like :

```python
# ext/schema/schema.py
class Schema:
    def __init__(self, app, title, plugins=None, docs_route=None,...):
        self.app = app
        self.schemas = {}
        ...
        if self.openapi_version:
            self.app.add_route(self.openapi_route, self.schema_response)
        if self.docs_route:
            self.app.add_route(self.docs_route, self.docs_response)
        ...

    @property
    def openapi(self):
        return self._apispec.to_yaml()

    def add_schema(self, name, schema, check_existing=True):
        ...

    def schema(self, name, **options):
        def decorator(f):
            self.add_schema(name=name, schema=f, **options)
            return f
        return decorator

    @property
    def docs(self):
        ...
        return template.render(...)

    def docs_response(self, req, resp):
        resp.html = self.docs

    def schema_response(self, req, resp):
        resp.status_code = status_codes.HTTP_200
        resp.headers["Content-Type"] = "application/x-yaml"
        resp.content = self.openapi

# app.py
api = responder.API()

schema = Schema(app=api, title="Web Service", plugins=[MarshmallowPlugin()])

@schema.schema("Pet")
class PetSchema(marshmallow.Schema):
    name = fields.Str()

@api.route("/")
def route(req, resp):
    """A cute furry animal endpoint.
    ---
    get:
        description: Get a random pet
        responses:
            200:
                description: A pet to be returned
                schema:
                    $ref: "#components/schemas/Pet"
    """
    resp.media = PetSchema().dump({"name": "little orange"})
```

**Comment by iancleary** [comment]
@taoufik07 I like the idea of moving grouped components into classes, either in `ext` folder or possibly into other modules at the same level as api.py (as appropriate).

When I was working on https://github.com/taoufik07/responder/pull/374, following the order of required code blocks and their order in the __init__ function was complicated. I'd be happy to retract the PR and help refactor the __init__. I agree it's worth doing and would like to help.

Besides Schema moving to #ext/schema/schema.py, what are your thoughts on route handling for the application (not the Route class but how the api handles adding routes, the static route, and being behind a reverse proxy).  I'd like to allow responder to be placed behind a reverse proxy, but my current solution adds bloat to the API.__init__.

My thought is to co-locate the code creating routes by moving what can be moved to the routes.py module  or generally approach separating the directory creation code (static and templates) and the route generation from the application/host settings and other private functions that appear to make the most sense in the API class.  What would you like to see?

**Comment by taoufik07** [comment]
Thanks @iancleary,

For now we try to move to asgi 3 (ref #379) to reduce the tech dept and organize a bit the project.

Next we try to decouple the app and agree on some extensions/plugins/modules pattern (I think the one above can do it since it's the most common pattern) and one of the extensions could be `static` in which we add the logic of dealing with static files.   

Regarding the routing and separation of concerns, I'm thinking of having some sort of router that can take care of matching and calling the routes.

**Comment by iancleary** [comment]
@taoufik07 it seems the refactor for [Schema](https://github.com/taoufik07/responder/blob/master/responder/ext/schema/__init__.py) and [Router](https://github.com/taoufik07/responder/blob/master/responder/routes.py) is complete in master. Nice work!

I can take a shot at Static if you'd like, let me know

I am going to work on the reverse proxy against the new Router class's add_route function mentioned in https://github.com/taoufik07/responder/issues/274

**Comment by taoufik07** [comment]
Thanks @iancleary, you contribution is much appreciated :D
