### ISSUE TITLE
Recommended way to change request method before handler

### ISSUE THREAD

**Issue by smashnet** [kennethreitz/responder#358]
What I'm trying to achieve is that a POST request with certain params will be treated as a DELETE request. (Doing this for users w/o JavaScript)

```html
<form method="POST" action="/posts/{{ post.uuid }}">
  <input type="hidden" name="_method" value="DELETE">
  <input type="hidden" name="_entry_id" value="{{ post.uuid }}">
  <button type="submit" class="btn btn-outline-danger">Delete</button>
</form>
```

I thought I could just go with

```python
@api.route(before_request=True)
async def check_hidden_method(req, resp):
  if req.method == "post":
    data = await req.media()
    try:
      if data['_method'].lower() in ["delete", "put", "patch"]:
        req.method = data['_method']
        print("Changed request method to", data['_method'])
    except KeyError:
      pass
```

... but it says I "can't set attributes" when trying `req.method = data['_method']`.

What is the recommended way to have that request processed by my on_delete()?

**Comment by taoufik07** [comment]
The recommended way is to use the DELETE method

**Comment by smashnet** [comment]
Using HTML forms I can only use GET and POST. And as Rails is able to handle hidden ˋ_methodˋ input fields as used in the example above, I hoped we can have a similar solution with responder.

**Comment by taoufik07** [comment]
Sorry I didn't pay attention.

I suggest to use a dedicated endpoint for delete `/posts/{pk}/delete/`, altering the method is not a good practice.

If you wanna stick with the `_method`, you can do something like
```python
async def articles(req, resp):
   ....
   if data['_method'].upper() == "DELETE":
       delete_article(req, resp)
   elif data['_method'].upper() == "PUT":
        update_article(req, resp)
   ...
```
or with CBV
```python
class Article:
	def on_post(self, req, resp):
		....
		if data['_method'].upper() == "DELETE":
			self.delete_article(req, resp)
		elif data['_method'].upper() == "PUT":
			self.update_article(req, resp)
		....

	def delete_article(self, req, resp):
		...
```
