### ISSUE TITLE
Is it possible to deploy responder to IIS using wfastCGI?

### ISSUE THREAD

**Issue by luongdieu86** [kennethreitz/responder#360]
Hi all,

I want to deploy responder to ISS (Windows 10) using wfastCGI but it's failed.
wfastcgi==3.0.0
responder==1.3.1

It's ok when I'm deploy Flask. 
But responder got following error :
```
Error occurred:

Traceback (most recent call last):
  File "D:\Dev_env\Python3.7.2_32bit\Lib\site-packages\wfastcgi.py", line 847, in main
    result = handler(record.params, response.start)
TypeError: __call__() takes 2 positional arguments but 3 were given


StdOut: 

StdErr:
```
Does this mean that wfastCgi does not support for Responder Router ?
How can I deploy responder app to IIS ?
Thank you

**Comment by taoufik07** [comment]
Hey, responder is an ASGI framework and I think wfastcgi only bridge to WSGI

**Comment by luongdieu86** [comment]
@taoufik07 is there any replacement for wfastcgi ? Dose uvicorn do the magic ?

**Comment by taoufik07** [comment]
yep

**Comment by luongdieu86** [comment]
Base my understanding, wfastcgi can act as a IIS - WSGI handler.
But Daphne, Uvicorn and Hypercorn are ASGI - servers. 
Can we use ASGI server as IIS - WSGI handler ? I can not found any document/guide about deploy ASGI on IIS.

**Comment by schap-dev** [comment]
I want to similar thing too.
I 'm exploring way to migration Flask to Responder.
I deployed Flask by [this simple way](http://flask.pocoo.org/docs/1.0/deploying/cgi/). How I can deploy Responder project without Docker and Heroku like this?
