### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by mtcronin99** [kennethreitz/responder#361]
In the Feature Tour (tour.rst) under the Trusted Hosts heading, shouldn't

`    api = responder.API(allowed_hosts=[example.com, tenant.example.com])
`

be

`    api = responder.API(allowed_hosts=['example.com', 'tenant.example.com'])
`

with quotes around the host names.

**Comment by taoufik07** [comment]
Hey, nice catch, if you want, you can make a PR !

**Comment by taoufik07** [comment]
Closed via #362
