### ISSUE TITLE
Issue with multiple endpoints

### ISSUE THREAD

**Issue by ssoto** [kennethreitz/responder#37]
Hi,
I implemented two simple endpoints:

```python
import responder

api = responder.API()

@api.route("/api/async")
async def api_async_test1(req, resp):
    resp.text = "{'status': 'OK'}"

@api.route("/api/test1")
def api_test1(req, resp):
    resp.text = "{'status': 'OK'}"

@api.route("/api/test2")
def api_test2(req, resp):
    resp.text = "{'status': 'OK'}"

if __name__ == '__main__':
    api.run()

```

Then I test endpoint behaviour:
```
$ curl http://127.0.0.1:5042/api/async
{"status": "OK"}

$ curl http://127.0.0.1:5042/api/test1
Not found.

$ curl http://127.0.0.1:5042/api/test2
Not found.
```

I discovered that issue is related with more than one api.route decorator added. It appears that only first route is found. Changing order, P.E.: switching first with second, makes new first route works.

I'm not sure if I am doing something wrong.

Regards!

**Comment by ssoto** [comment]
After a little debugging I found that your memoize decorator is not working nice.

**Comment by ssoto** [comment]
I had forked repo in order to shed light on this issue:
https://github.com/ssoto/responder/commit/4a0641347fd9436fb5392f0eae891d8b51ec41bf

**Comment by kennethreitz** [comment]
removed memoization

**Comment by ssoto** [comment]
Should tests validate It?
