### ISSUE TITLE
How to split a server in modules

### ISSUE THREAD

**Issue by svdh2** [kennethreitz/responder#408]
I am trying to split a server into multiple modules and I am running into troubles:

- I did put the example of the OpenAPI Schema Support example into the file rest/demo_api.py

- In order to get it working I had to start the responder server before importing that module.

```
import responder
api = responder.API()
from rest.demo_api import *
api.run()
```
At that point I can call the endpoints but the specs fail as marshmallow cannot properly bind back to the PetSchema class.

So my question is responder designed to split the server into multiple modules ? If yes what is the proper way so people would not run into the issues I am seeing?

**Comment by StevenAvelino24** [comment]
Hello,
Could you provide a bit more information on this ?
Did you mean that you needed to init Responder ? (so doing `responder.API()`)
Can you also provide the rest/demo_api.py file you used ?

Thank you :)
