### ISSUE TITLE
Docs: being more explicit about why to use api.background.task

### ISSUE THREAD

**Issue by butla** [kennethreitz/responder#418]
Hey! When I was reading the docs and I saw `api.background.task`, the first thing that popped into my head was "but you can just use `asyncio.create_task` or `loop,.run_in_executor` for that without inventing something new!". But then I noticed that it also passes the context vars to the synchronous backround stuff, which is nice. Wonder why that's not the case in the stdlib, cause it would be nice :)

All I'm asking is: would you welcome a docs PR explaining `api.background.task` to asyncio purists like myself? :)

**Comment by taoufik07** [comment]
Yes, we would love to !

**Comment by butla** [comment]
Nice. I'll try to write something up in the next few days
