### ISSUE TITLE
Potential code quality improvements

### ISSUE THREAD

**Issue by pnijhara** [kennethreitz/responder#435]
I forked this repo and ran a DeepSource analysis over it.
There:
- 12 Antipattern issues were found
- 4 Bug-Risks issues were found
- 1 Performance issue was found
- 31 Security issues were found
---
Out of which 22 can be auto fixed. Some of them can be found here
- https://deepsource.io/gh/pnijhara/responder/issue/PYL-W0611/
- https://deepsource.io/gh/pnijhara/responder/issue/PYL-W0613/
- https://deepsource.io/gh/pnijhara/responder/issue/BAN-B101/
---
In all total number of issues are listed here - https://deepsource.io/gh/pnijhara/responder/

Link to `.deepsource.toml` configuration file that was added to the forked repo for running DeepSource analysis can be found [here](https://github.com/pnijhara/responder/blob/pnijhara-patch-1/.deepsource.toml)

Which of these issues you would consider high priority, and which ones would you want to ignore or consider false-positive?

I can send a PR with some fixes if you want.
You can also activate this analysis on your own, and have it triggered on each PR if you integrate [DeepSource](https://deepsource.io) in the repo

Disclaimer: I work for DeepSource

**Comment by pnijhara** [comment]
cc @taoufik07 @ken-reitz 
What do you think?

**Comment by taoufik07** [comment]
Hey @pnijhara, thanks for this tool ! for now let's just create PRs to fix the potential code quality improvements, the security and bug issues are on high priority.

**Comment by pnijhara** [comment]
Sure!
I will open issues for discussion on security and bug-risk issues.

**Comment by pnijhara** [comment]
@kennethreitz do you want me to work on this?

**Comment by kennethreitz** [comment]
sure!
