### ISSUE TITLE
api.jinja_values_base removed?

### ISSUE THREAD

**Issue by aiotter** [kennethreitz/responder#438]
Although the docs says `api.jinja_values_base` is [valid](https://responder.kennethreitz.org/en/latest/api.html#responder.API.template), it seems `api.jinja_values_base` has removed from code.
Is this removed completely? Do you have any plan to provide other means to set default values to pass to jinja2?

**Comment by sepulworld** [comment]
Running into similar issue

```api.jinja_env.filters['tojson_pretty'] = to_pretty_json```

```
       Traceback (most recent call last):
         File "/app/dinghy_ping/services/api.py", line 69, in <module>
           api.jinja_env.filters['tojson_pretty'] = to_pretty_json
       AttributeError: 'API' object has no attribute 'jinja_env'
```

**Comment by sepulworld** [comment]
I tried switching over to `api.jinja_values_base` but doesn't seem to be a valid interface.

```       
Traceback (most recent call last):
         File "/app/dinghy_ping/services/api.py", line 69, in <module>
           api.jinja_values_base['filters']['tojson_pretty'] = to_pretty_json
       AttributeError: 'API' object has no attribute 'jinja_values_base'
```

Trying to update to responder 2.0.5
