### ISSUE TITLE
official way to run webpack!

### ISSUE THREAD

**Issue by devxpy** [kennethreitz/responder#46]
In light of this "future work"

> If frontend websites are supported, provide an official way to run webpack.

I would like to propose a merger of my project,  [react-pages](https://github.com/pycampers/react-pages) which runs an ejected create-react-app from a python interface.

All insults are welcome!

**Comment by kennethreitz** [comment]
turning away from this, for now. we'll see if it's needed. 

thanks for the suggestion!
