### ISSUE TITLE
Lean on Starlette.

### ISSUE THREAD

**Issue by tomchristie** [kennethreitz/responder#50]
Opening this issue first for discussion rather than just jumping in, because I want to understand where @kennethreitz would like to draw the boundaries on this.

There's currently quite a lot of duplication between Starlette and Responder. Starting with one class to consider there's [`responder.Response`](https://github.com/kennethreitz/responder/blob/master/responder/models.py#L103)...

* `headers` - Exposes a case-insensitive dict. Starlette already has a `request.headers` which is a case-insensitive multidict.
* `method` - Exposes the request method, lowercased. Starlette already exposes this, uppercased, as `request.method`.
* `.full_url`, `.url` - Exposes the str-URL and parsed URL. Starlette already exposes a str-like interface that also allows accessing parsed components on it. `request.url`, `request.url.path`, etc...
* `.params` - Exposes a QueryDict. Starlette already exposes a query param multidict, as `request.query_params`.

(For reference here's Starlette's request docs... https://www.starlette.io/requests/)

Ideally we'd try to minimize reproducing too much stuff in differing interfaces. Or at least work towards having the data-structures be Starlette's low-level stuff, while Responder uses whatever high-level `request` interface it wants to stitch those together. (Ie. try to ensure that Starlette is to Responder as Werkzeug is to Flask.)

Initial thoughts?

**Comment by kennethreitz** [comment]
I want the coupling to be loose, unlike that of flask/werkzeug.
