### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by tomchristie** [kennethreitz/responder#51]
Supporting ASGI middleware would be a really good way to compartmentalise away bits of complexity, as we all promoting more of a cross-framework ecosystem.

I'd suggest an interface of `app.add_middleware(cls, **options)`

We could then do things like:

* Move the GZip handling out of `Response`, and use `Starlette`'s GzipMiddleware, which will also take care of handling streaming responses (once responder has those)
* Be able to use Starlette's `CORSMiddleware`.

We can set up a default set of middleware if needed based on the configuration options presented to the `API(...)` class.

Any objections or considerations?

**Comment by kennethreitz** [comment]
I'm open to that:

```
    def add_middleware(self, middleware_class, **options):
        self.middleware.append(middleware_class(self, **options))
```

**Comment by tomchristie** [comment]
Also useful here - Starlette's `ExceptionMiddleware`

**Comment by ajitid** [comment]
Hey, any idea how to turn on debug mode in Responder?

**Comment by kennethreitz** [comment]
@ajitid it doesn't have it yet :)

**Comment by tomchristie** [comment]
Run it using `uvicorn --debug example:app` and you'll get in-browser tracebacks on exceptions.

`uvicorn.run(..., debug=True)` if we want the same thing programmatically.

**Comment by ajitid** [comment]
I already tried programmatically, it didn't worked though.

```python
import responder

api = responder.API()

@api.route('/')
def home(req, res):
    res.text = "This should work, right?"

if __name__ == '__main__':
    api.run(debug=True)
```

Something like this, na?
`api.run()` does pass all kwargs to `uvicorn.run()`, but for some reason it isn't able to turn debug mode on.

**Comment by ajitid** [comment]
> The reloader is not enabled when running programmatically.

Didn't knew this, and was getting confused.
