### ISSUE TITLE
Frontend website strategy

### ISSUE THREAD

**Issue by metakermit** [kennethreitz/responder#53]
Really like the concepts inside responder! I'm wondering what would be the strategy for integrating frontend websites? I see webpack is mentioned in the README. Would something like https://parceljs.org/ also be interesting? Since the choice of frontend framework / tooling is pretty tangental to other things in responder, would it maybe make sense to just round up a few example folders or cookiecutters and link them up? E.g.

- responder + webpack + react
- responder + parcel + react
- responder + angular

One thing that would make sense to standardise IMHO would be the build command in package.json. E.g. always have an `npm run build` command for building the frontend. That way a standard responder Heroku buildpack / Dockerfile could be used for deploying the webapp no matter which frontend stack is used.

**Comment by e-ht** [comment]
Whether or not tight front end integration gets put on the back burner I think it's a really important premise to have a roadmap for.  With how fast and loose front end can be it would be advantageous to have a standardized build method as you mentioned.

**Comment by kennethreitz** [comment]
I like that.

**Comment by kennethreitz** [comment]
running 'npm build' that is.

**Comment by metakermit** [comment]
OK, great! I'll see if I can cook up a nice working example with Parcel + React and then we can talk about an official buildpack / Dockerfile or something that would run `npm install` / `npm run build` if there's a *package.json* and therefore encode this standard 🙂.

**Comment by metakermit** [comment]
As a first baby step, I've made a very minimal React + Parcel example featuring:

- ES6 modules
- image importing
- frontend routing (using [React-Router][react-router])

To deploy it's enough to do `npm install` & `npm run build` which packages everything in a dist folder ready for serving.

Here's the code:

https://github.com/metakermit/responder-react

I haven't touched any Responder stuff so far, but I see that there are going to be some challenges. Some challenges as far as I see:

- it should be possible to serve static files on `/` instead of `static/`
- `/` should serve index.html
- all urls not found in Responder's own routes should be forwarded to index.html (which would be needed for [frontend routing][react-router])

Starlette should have options for some of these things, but I think they aren't all exposed in Responder. As a side-note, I did solve some of these issues with Django & Whitenoise [here](https://github.com/metakermit/django-spa), so I have some ideas for how these things could be solved. Not sure what the best approach would be in Responder architecture-wise.

[react-router]: https://reacttraining.com/react-router/web/guides/philosophy

**Comment by kennethreitz** [comment]
Now, off master, if you do this:

```python
api.add_route("/", static=True)
```
static's `index.html` will automatically be responded with.

**Comment by kennethreitz** [comment]
Now, off master, if you have a `static=True` route, all routes will be forwarded to static `index.html` responder.

**Comment by kennethreitz** [comment]
this still leaves
> it should be possible to serve static files on / instead of static/

but I think that's a small workaround, for now.

**Comment by metakermit** [comment]
@kennethreitz Perfect, that solves most of the SPA requirements, I think 🎉 I'll test it and if it works, we can later see if we want to have some order of precedence in the future, e.g. in the `static=True` mode:

1. check responder routes first (e.g. for some `/api/users/` endpoints etc.)
2. if there aren't any, redirect everything to index.html to handle
3. the frontend then checks its routing and is responsible for the 404 page etc.

**Comment by kennethreitz** [comment]
@metakermit that's exactly the flow that's in place.

**Comment by kennethreitz** [comment]
I don't know much about single-page web apps, but this will always result in a 200 response from the server, even if it appears as though it's 404.

**Comment by kennethreitz** [comment]
unless there's a specific 404 view defined

**Comment by kennethreitz** [comment]
cool, i'll ship it :shipit:

**Comment by kennethreitz** [comment]
v0.1.0 released, which includes this.

**Comment by metakermit** [comment]
Sure, I think that's fine. I think the way it's done is that if the frontend doesn't find its template, it renders a 404 page. Traditionally this is done by [setting nginx to forward everything to index.html](https://stackoverflow.com/a/43954597/544059), but with Responder we don't need nginx 🙂 

Awesome! 🚀
