### ISSUE TITLE
GAE support

### ISSUE THREAD

**Issue by marban** [kennethreitz/responder#56]
Any general thoughts on using this on App Engine?

**Comment by kennethreitz** [comment]
what special support is needed?

**Comment by tomchristie** [comment]
Might be problematic, since I expect that GAE is strictly a WSGI environment.

**Comment by gbgduh** [comment]
hey @marban, in the new py3 runtime in GAE Std you can specify an entrypoint in the `app.yaml` like:
```entrypoint: "gunicorn --log-level debug --bind :$PORT --reuse-port --workers 2 --worker-class uvicorn.workers.UvicornWorker server:app"```. It seems to be working for me.
Flex can even work with munal docker file.
