### ISSUE TITLE
optional dependencies

### ISSUE THREAD

**Issue by carlwgeorge** [kennethreitz/responder#64]
This project has 16 dependencies (as of 0.0.7), and many of those have their own dependencies.  Installing responder in a virtual environment results in 32 libraries being installed.  This also makes packaging responder more time consuming for Linux distros.

I'm sure each of those has their own reason for being there, but have you considered allowing a more minimal install?  Setuptools has an `extras_require` argument where optional dependencies that enable extra functionality can be specified.

**Comment by kennethreitz** [comment]
that comes with the territory, unforunately
