### ISSUE TITLE
JSON string encoding option on resp.media

### ISSUE THREAD

**Issue by reilly3000** [kennethreitz/responder#74]
I was able to really quickly develop a simple API using Responder and Records, and am generally loving life right now. However, I need to return a json object instead of a json string. When I run:

```
@api.route("/")
def hello(req, resp):
resp.media = {'myJSON': 'object'}
 ``` 
I get a JSON object back

```
@api.route("/top-10/{date}")
def top(req, resp,date):
    rows = db.query('''myquery ''', date=date)
resp.media = rows.export('json')
``` 
I get a JSON string 

Are there any arguments I could pass to change the format?

**Comment by kennethreitz** [comment]
rows.as_dict()
