### ISSUE TITLE
ORM integration

### ISSUE THREAD

**Issue by bartlomieju** [kennethreitz/responder#77]
I would love to see some simple ORM integration. It would make `responder` great alternative to Django for hacking quick projects.

**Comment by reilly3000** [comment]
Kenneth also made an awesome, simple SQL library called Records that allows for parameterized SQL. I just used it when taking Responder for a test spin. Could something like this meet your needs?

```
import responder
import records

api = responder.API()
db =records.Database('postgres://connection string')

@api.route("/url/{myparam}")
def top(req, resp,myparam):
    rows = db.query('''select * from table where param = :param ''', param=myparam)
    resp.media = rows.export('json')
```

**Comment by bartlomieju** [comment]
@reilly3000 awesome thanks!

**Comment by martincolladodotcom** [comment]
Or maybe in the future create an extension for gino https://github.com/fantix/gino
