### ISSUE TITLE
errors from background tasks are not printed 

### ISSUE THREAD

**Issue by bartlomieju** [kennethreitz/responder#78]
Given:
```
import responder
# import time <- notice missing import

api = responder.API()

@api.route("/")
def hello(req, resp):

    @api.background.task
    def sleep(s=1):
        time.sleep(s)
        print("slept!")

    sleep()
    resp.content = "processing"

if __name__ == '__main__':
    api.run()
```

When running `sleep` `NameError` is thrown but no output is shown in console.

**Comment by kennethreitz** [comment]
we need to add logging.

**Comment by condemil** [comment]
The exception is happening in separate thread that is the reason it is not printed.

@kennethreitz What do you think will be the best approach to handle exception in futures? It is possible to have a custom ThreadPoolExecutor as it is proposed [here](https://stackoverflow.com/a/24457608/2609424).

**Comment by e-ht** [comment]
@condemil a custom ThreadPoolExecutor would work for handling exceptions, but the value proposition of needing to take action beyond just logging the error doesn't exist IMO. 

Having general logging that the bg tasks could tap in to would be more generically valuable.

**Comment by vuonghv** [comment]
@kennethreitz What about passing callback functions to `@api.background.task` to handle success and error case. I'm implementing this feature, and the following is demo api:
```python
def on_success(result):
     print(result)

def on_error(error):
    print(error)

@api.background.task(on_success, on_error)
def sleep(s=10):
     // Do background tasks here

```

**Comment by kennethreitz** [comment]
I feel if you want something more sussinct, you should just use async/await
