### ISSUE TITLE
Proposal: on_request should not be called when on_{method} is defined

### ISSUE THREAD

**Issue by 3lpsy** [kennethreitz/responder#79]
Upon reviewing the source code, I noticed that on_request runs on each request even if on_{method} ( like on_get) is defined. I propose to change this so that only on_{method} is called and on_request is not called if on_{method} is defined. 

I've already made this change on this fork: https://github.com/3lpsy/responder/tree/no-default-request-with-method 

At first I thought this was unintentional; however, after reviewing the tests, it seems like this is intended behavior. I understand that the benefit of having on_request run on each request even if on_{method} is defined is useful for calling common functionality that runs on different methods; however, I think this is less intuitive.  

I wanted to make this issue before creating a PR in case I do not fully understand the benefit of keeping this behavior.

**Comment by kennethreitz** [comment]
disagree

**Comment by kennethreitz** [comment]
thank you for your feedback, though!
