### ISSUE TITLE
Contributions welcome!

### ISSUE THREAD

**Issue by kenneth-reitz** [kennethreitz/responder#9]
In the spirit of [Hacktoberfest 2018](https://hacktoberfest.digitalocean.com/), I'd like to open this repository to all contributions!

![hacktoberfest](https://hacktoberfest.digitalocean.com/assets/hacktoberfest-2018-social-card-c8d2e1489f647f2e0a26e6f598adeb760872818905b34cd437afc7ac2857ceab.png)

Try to open an issue before doing too much work, for discussion.

**Comment by rbidanta** [comment]
I would like to contribute. How can I help?

**Comment by nicolas471** [comment]
Hi, how can I contribute?

**Comment by pykong** [comment]
How could we coordinate our contributions best?
Maybe having some channel on `slack || dicord || gitter` would be helpful.

**Comment by VighneshKSP** [comment]
This invite is not valid anymore. Hence closing the ticket.
