### ISSUE TITLE
Possible name conflict

### ISSUE THREAD

**Issue by dontomm1** [kennethreitz/responder#92]
As much as I love the name `responder` for a web framework (and especially one from the author of `requests`), it appears that the name `Responder.py` is already taken by a security tool (see https://github.com/SpiderLabs/Responder), and a google search for `python responder` will yield that project as the top result.

This is meant just as a heads-up and nothing more. Personally, I would like it very much for this project to keep its name.

**Comment by kennethreitz** [comment]
I'm aware of the other name. They're `responder.py`, we're `responder`. I think we're in the clear. 👍
