### ISSUE TITLE
Could not find a version that matches apispec>=1.0.0b1 using pipenv install for project setup

### ISSUE THREAD

**Issue by jboegeholz** [kennethreitz/responder#93]
I'm trying to set up my first responder app using pipenv.
The application works, but due to the error during pipenv install no Pipfile.lock is generated.

Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
responder = "*"

[dev-packages]

[requires]
python_version = "3.6"

**Comment by kennethreitz** [comment]
I think you need --pre
